services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
        - ./nuxt:/usr/src/app
    environment:
      - APP_ENV=${APP_ENV}
      - SENTRY_DSN=${SENTRY_DSN}
      - RELEASE_ID=${RELEASE_ID}