services:
  web:
    image: nginx
    volumes:
      - ./nginx/public-2:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=ubuntu.local
      - NGINX_PORT=8081
    networks:
      experiment:
        aliases:
          - web2.experiment

networks:
  experiment: