services:
  web:
    image: nginx
    volumes:
      - ./template-1/default.conf:/etc/nginx/templates/default.template
      - ./nginx/public-1:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
      - "8081:81"
    environment:
      - NGINX_HOST=macos.local
      - NGINX_PORT=8080
    networks:
      experiment:
        aliases:
          - web1.experiment

networks:
  experiment: