services:
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ./nginx/public-2:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=macos.local
      - NGINX_PORT=8080
    networks:
      - experiment

networks:
  experiment: