version: '3.8'

services:
  nginx-1:
    image: nginx
    restart: 'always'
    volumes:
      - ./template-1/default.conf:/etc/nginx/templates/default.template
      - ./nginx/public-1:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=macos.local
      - NGINX_PORT=8080
    networks:
      experiment:
        aliases:
          - web1.experiment
    deploy:
      replicas: 1
      endpoint_mode: vip

  nginx-2:
    image: nginx
    restart: 'always'
    volumes:
      - ./nginx/public-2:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=ubuntu.local
      - NGINX_PORT=8081
    networks:
      experiment:
        aliases:
          - web2.experiment
    deploy:
      replicas: 1
      endpoint_mode: vip

networks:
  experiment: