version: '3.8'

services:
  nginx-1:
    image: nginx
    volumes:
      - ./nginx/template-1/default.conf:/etc/nginx/templates/default.conf.template
      - ./nginx/public-1:/usr/share/nginx/html:ro
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
      - target: 8081
        published: 81
        protocol: tcp
        mode: host
    networks:
      experiment:
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==host1"

  nginx-2:
    image: nginx
    volumes:
      - ./nginx/template-2/default.conf:/etc/nginx/templates/default.conf.template
      - ./nginx/public-2:/usr/share/nginx/html:ro
    networks:
      experiment:
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==host2"

networks:
  experiment:
    driver: overlay
    attachable: true