execution:
  - concurrency: 50
    ramp-up: 20s
    hold-for: 1m
    scenario: IndexPage

scenarios:
  IndexPage:
    default-address: https://test-3.#
    requests:
      - /
      - /courses
      - /blog
      - /api/test/healthcheck