services:

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - TARGET_HOST=yaizy.io
    volumes:
      - ./nginx/default.conf.http.template:/etc/nginx/templates/default.conf.template
    depends_on:
      - proxy-cache

  proxy-cache:
    image: "node:20"
    working_dir: /var/www/app/
    volumes:
      - ./proxy-cache:/var/www/app/
    environment:
      - TARGET_HOST=yaizy-io.framer.website
      - PROXY_PORT=8081
    expose:
      - 8081:8081
    #command: "npm start"
    command: "npm run dev"
    depends_on:
      - redis

  redis:
    image: redis:latest
    expose:
      - 6379:6379
    #environment:
      #- REDIS_PASSWORD=password
      #- REDIS_PORT=6379
      #- REDIS_DATABASES=1