services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5
    volumes:
      - ./config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  webserver:
    image: nginx
    environment:
      - PORT=3000
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf.http.template:/etc/nginx/templates/default.conf.template
    ports:
      - 3000:3000